// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVHnlNVhrGNZMyxKCU6zr-BFq0XFu3IKU',
    appId: '1:241732383553:android:7e1f4798d51df75c3fe7c0',
    messagingSenderId: '241732383553',
    projectId: 'weather-app-5a12e',
    databaseURL: 'https://weather-app-5a12e-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-5a12e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv5Te7Keqtc6S6PiWlOfC9WdcnL3DOOrc',
    appId: '1:241732383553:ios:fd83843fe2d909803fe7c0',
    messagingSenderId: '241732383553',
    projectId: 'weather-app-5a12e',
    databaseURL: 'https://weather-app-5a12e-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-5a12e.appspot.com',
    androidClientId: '241732383553-eh5gl2q1q17qu9atgjond8hct29nl39o.apps.googleusercontent.com',
    iosClientId: '241732383553-eq80u5heqkf3774fqsgr99rkhfdur3ii.apps.googleusercontent.com',
    iosBundleId: 'br.com.rochajohnathan.weatherApp',
  );
}
